/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package penjualan.view;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import penjualan.entity.PieChartModel;
import penjualan.koneksi.KoneksiSql;

public class StatistikView extends javax.swing.JFrame {

    /**
     * Creates new form StatistikView
     */
    public StatistikView() {
        initComponents();
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
                
        pieChartBarang.setChartType(penjualan.panel.PieChart.PeiChartType.DONUT_CHART);
        getPenjualanBarangData();
    }

    void getPenjualanBarangData() {
        try {
            Statement st = KoneksiSql.getKoneksi().createStatement();
            ResultSet rs = st.executeQuery("SELECT concat(kode_barang, '-', nama_barang) as nama_barang, sum(transaksi.jumlah) as jumlah FROM transaksi join barang on barang.kode_barang = transaksi.id_barang group by kode_barang;");
            while (rs.next()) {
                pieChartBarang.addData(new PieChartModel(rs.getString("nama_barang"), rs.getInt("jumlah"), new Color((int) (Math.random() * 0x1000000))));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mendapat data dari database \n" + e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pieChartBarang = new penjualan.panel.PieChart();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Presentase Pembelian Barang");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pieChartBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel1)
                .addGap(78, 78, 78)
                .addComponent(pieChartBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private penjualan.panel.PieChart pieChartBarang;
    // End of variables declaration//GEN-END:variables
}
