package penjualan.panel;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import penjualan.entity.TransaksiEntity;
import penjualan.implement.TransaksiImplement;
import penjualan.interfc.TableDataInterface;
import penjualan.view.StatistikView;

public class LaporanPanel extends javax.swing.JPanel {
    List<TableDataInterface> listTransaksi = new ArrayList();

    TransaksiEntity emptyTransaksi = new TransaksiEntity();
    TransaksiEntity selectedTransaksi = null;
    TransaksiImplement transaksiImplement = new TransaksiImplement();

    /**
     * Creates new form LaporanPanel
     */
    public LaporanPanel() {
        initComponents();
        
        getListTransaksi();
        
        tableTransaksi.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                if (!event.getValueIsAdjusting() && tableTransaksi.getSelectedRow() != -1) {
                    if (tableTransaksi.getValueAt(tableTransaksi.getSelectedRow(), 0) != null) {
                        int indexSelected = Integer.parseInt(tableTransaksi.getValueAt(tableTransaksi.getSelectedRow(), 0).toString()
                        );
                        setFieldValueAsSelectedRow(indexSelected - 1);
                    }
                }
            }
        });
    }
    
    
    void getListTransaksi() {
        DefaultTableModel dtm = new DefaultTableModel(null, emptyTransaksi.getHeader());
        try {
            listTransaksi = transaksiImplement.getAll();
            for (int i = 0; i < listTransaksi.size(); i++) {
                dtm.addRow(listTransaksi.get(i).toTableRowWithIndex(i));
            }
            tableTransaksi.setModel(dtm);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mendapat data dari database \n" + e.getMessage());
        }
    }

    void setFieldValueAsSelectedRow(int index) {
        selectedTransaksi = ((TransaksiEntity) listTransaksi.get(index));

        kodeBarangField.setText(selectedTransaksi.getKodeBarang());
        namaBarangField.setText(selectedTransaksi.getNamaBarang());
        idPelangganField.setText("" + selectedTransaksi.getJumlah() + "");
        namaPelangganField.setText(selectedTransaksi.getNamaPelanggan());
    }

    void hapusData() {
        if (selectedTransaksi != null) {
            int confirm = JOptionPane.showConfirmDialog(this, "Anda yakin ingin menghapus barang  " + selectedTransaksi.getIdTransaksi(), "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (confirm == 0) {
                try {
                    transaksiImplement.delete(String.valueOf(selectedTransaksi.getIdTransaksi()));
                    JOptionPane.showMessageDialog(this, "Berhasil menghapus data dari database");
                    kodeBarangField.setEnabled(true);
                    getListTransaksi();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus data dari database \n" + e.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Mohon pilih barang dalam tabel untuk melakukan penghapusan");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableTransaksi = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        idPelangganField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        namaPelangganField = new javax.swing.JTextField();
        statistik = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        kodeBarangField = new javax.swing.JTextField();
        namaBarangField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        tableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Jumlah", "Harga", "Sub Total", "Nama", "Alamat", "No Telp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableTransaksi);

        idPelangganField.setEditable(false);
        idPelangganField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPelangganFieldActionPerformed(evt);
            }
        });

        jLabel15.setText("ID Pelanggan");

        jLabel16.setText("Nama Pelanggan");

        namaPelangganField.setEditable(false);

        statistik.setText("Statistik");
        statistik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statistikMouseClicked(evt);
            }
        });
        statistik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statistikActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(statistik)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idPelangganField)
                            .addComponent(namaPelangganField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(idPelangganField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(namaPelangganField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(statistik)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel13.setText("Kode Barang");

        kodeBarangField.setEditable(false);

        namaBarangField.setEditable(false);

        jLabel14.setText("Nama Barang");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kodeBarangField, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(namaBarangField))
                        .addGap(64, 64, 64)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(kodeBarangField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(namaBarangField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void idPelangganFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPelangganFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idPelangganFieldActionPerformed

    private void statistikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statistikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statistikActionPerformed

    private void statistikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statistikMouseClicked
            new StatistikView().setVisible(true);
    }//GEN-LAST:event_statistikMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idPelangganField;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kodeBarangField;
    private javax.swing.JTextField namaBarangField;
    private javax.swing.JTextField namaPelangganField;
    private javax.swing.JButton statistik;
    private javax.swing.JTable tableTransaksi;
    // End of variables declaration//GEN-END:variables
}
